// ./app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "New Hero Slider",
  description: "Generated by Muntasir using create next app",
  icons: {
    icon: "/favicon.ico", // Direct path to the favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* No need to manually link the favicon if it's specified in metadata */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
